ERROR:root:Authentication plugin 'caching_sha2_password' is not supported
ERROR:root:Authentication plugin 'caching_sha2_password' is not supported
ERROR:root:1045 (28000): Access denied for user 'alper_himself'@'176.41.31.61' (using password: YES)
ERROR:root:1045 (28000): Access denied for user 'alper_himself'@'176.41.31.61' (using password: YES)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 13:15:58] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 13:15:58] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 13:16:09] "[31m[1mGET /insertion HTTP/1.1[0m" 405 -
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:41:23] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:43:02] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:43:19] "[31m[1mGET /insertion HTTP/1.1[0m" 405 -
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:43:35] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:44:08] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:45:43] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 14:48:06] "[35m[1mGET /selection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 15:31:53] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:10:53] "[33mPOST /alert HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:11:11] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:19:27] "[35m[1mGET /selection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:27:13] "[35m[1mGET /selection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:27:48] "[35m[1mGET /selection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:37:37] "[35m[1mGET /selection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Detected change in 'C:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 16:56:07] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 17:03:10] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 17:03:36] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 17:05:13] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 17:10:19] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 17:10:52] "[37mGET /selection HTTP/1.1[0m" 200 -
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
INFO:werkzeug: * Restarting with stat
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
ERROR:root:1045 (28000): Access denied for user 'alperuser'@'176.41.31.61' (using password: YES)
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 290-975-934
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Detected change in 'c:\\Users\\Alper\\python101\\casestudy.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /deleting [DELETE]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: delete() missing 1 required positional argument: 'number'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 17:43:26] "[35m[1mDELETE /deleting HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /deleting [DELETE]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: delete() missing 1 required positional argument: 'number'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:02:00] "[35m[1mDELETE /deleting HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:29:31] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:32:18] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:33:32] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:35:40] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
ERROR:casestudy:Exception on /insertion [PUT]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:36:02] "[35m[1mPUT /insertion HTTP/1.1[0m" 500 -
ERROR:casestudy:Exception on /insertion [PUT]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:37:20] "[35m[1mPUT /insertion HTTP/1.1[0m" 500 -
ERROR:casestudy:Exception on /insertion [PUT]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:37:22] "[35m[1mPUT /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /selection [GET]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:38:32] "[35m[1mGET /selection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /deleting [DELETE]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: delete() missing 1 required positional argument: 'number'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 18:40:34] "[35m[1mDELETE /deleting HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:13:08] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:13:08] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:13:15] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:14:04] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:14:17] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: insert() missing 4 required positional arguments: 'name', 'lastname', 'location', and 'age'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:14:39] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alper\python101\casestudy.py", line 56, in insert
    ('{name}', '{lastname}', '{location}','{age}');"""
NameError: name 'lastname' is not defined
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:21:41] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alper\python101\casestudy.py", line 56, in insert
    ('{name}', '{lastname}', '{location}','{age}');"""
NameError: name 'lastname' is not defined
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:22:17] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:23:44] "[37mPOST /insertion HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:24:31] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:24:33] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:24:34] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:24:41] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
ERROR:casestudy:Exception on /deleting [DELETE]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alper\python101\casestudy.py", line 91, in delete
    return jsonify(json=number)
NameError: name 'number' is not defined
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:26:52] "[35m[1mDELETE /deleting HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:27:36] "[37mDELETE /deleting HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:27:45] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:27:49] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:27:53] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:27:57] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:28:01] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:28:07] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:28:43] "[37mDELETE /deleting HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:28:50] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:32:47] "[37mDELETE /deleting HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:33:03] "[37mGET /selection HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:34:00] "[31m[1mPOST /selection HTTP/1.1[0m" 405 -
INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:38:48] "[37mGET /selection HTTP/1.1[0m" 200 -
ERROR:casestudy:Exception on /insertion [POST]
Traceback (most recent call last):
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alper\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alper\python101\casestudy.py", line 47, in insert
    name = insertion["name"]
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:38:58] "[35m[1mPOST /insertion HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [25/Apr/2021 20:39:17] "[37mDELETE /deleting HTTP/1.1[0m" 200 -
